language: cpp

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script:
  - ./project build

matrix:
  exclude:
    # Only check clang on OS X
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang
      - g++-4.8
      - gcc-4.8
      - lcov
