language: cpp
compiler:
  - gcc
  - clang
matrix:
  - os: linux
    env: ARCH=x86_64
  - os: osx
script:
  - cmake -G "Unix Makefiles"
  - make && make install
  - export LD_LIBRARY_PATH=./build/lib/
  - export DYLD_LIBRARY_PATH=./build/lib/
  - ./build/bin/gallocy_tests
