language: cpp
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
script:
  - cmake -G "Unix Makefiles"
  - make && make install
  - export LD_LIBRARY_PATH=./install/lib/
  - export DYLD_LIBRARY_PATH=./install/lib/
  - ./install/bin/gallocy_tests
